"""Generated manuscript assets: tables, figure data, claim matrix, appendix.

Nothing here is written by hand into the manuscript. Every asset is emitted
either from an admitted sealed package or, before one exists, as an explicitly
unfilled scaffold whose slots the preflight refuses to pass. The scaffold is
not a placeholder in the loose sense: it has the exact final shape, the exact
final row set, and the exact final captions, so the only thing that changes
when results arrive is the values.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .errors import PackageRejected
from .package import SealedPackage

UNFILLED = r"\result{pending}"


@dataclass(frozen=True)
class Row:
    """One row of a generated table."""

    label: str
    keys: tuple[str, ...]


#: The co-primary and decomposition table. Keys are the emitted-number keys the
#: analysis must provide; the row set is frozen so a missing estimand is
#: visible as an unfilled cell rather than an absent row.
PRIMARY_ROWS: tuple[Row, ...] = (
    Row("$\\Delta_{\\text{content}}$ (co-primary)", ("content.estimate", "content.lower_bound", "content.p_value")),
    Row("$\\Delta_{\\text{excess}}$ (co-primary)", ("excess.estimate", "excess.lower_bound", "excess.p_value")),
    Row("$\\Delta_{\\text{sham\\_packet}}$", ("sham_packet.estimate", "sham_packet.lower_bound", "sham_packet.p_value")),
    Row("$\\Delta_{\\text{continuation}}$", ("continuation.estimate", "continuation.lower_bound", "continuation.p_value")),
    Row("$\\Delta_{\\text{total}}$", ("total.estimate", "total.lower_bound", "total.p_value")),
)

RESOLUTION_ROWS: tuple[Row, ...] = (
    Row("observed discordance $q_0$", ("resolution.q0",)),
    Row("resolution floor $r_{95}$", ("resolution.r95",)),
    Row("resampling drift $\\Delta_{\\text{null}}$", ("resolution.delta_null",)),
    Row("practical screen $\\delta^\\star$", ("resolution.delta_star",)),
)

ENVIRONMENT_ROWS: tuple[Row, ...] = (
    Row("repository repair", ("swe.content", "swe.excess", "swe.n")),
    Row("stateful tool/API dialogue", ("tau.content", "tau.excess", "tau.n")),
)


def _cell(package: SealedPackage | None, key: str) -> str:
    if package is None:
        return UNFILLED
    try:
        value = package.number(key)
    except PackageRejected:
        return UNFILLED
    if isinstance(value, float):
        return f"{value:.3f}"
    return str(value)


def _table(
    package: SealedPackage | None,
    *,
    label: str,
    caption: str,
    header: Sequence[str],
    rows: Sequence[Row],
) -> str:
    columns = "l" + "r" * (len(header) - 1)
    lines = [
        "% GENERATED by pneuma_lab.placebo_paper.render -- do not edit by hand.",
        "\\begin{table}[H]",
        "\\centering",
        "\\small",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{columns}}}",
        "\\toprule",
        " & ".join(header) + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        cells = [_cell(package, key) for key in row.keys]
        lines.append(" & ".join([row.label, *cells]) + " \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def primary_table(package: SealedPackage | None) -> str:
    return _table(
        package,
        label="tab:primary",
        caption=(
            "Co-primary estimands and required decompositions. Lower bounds are "
            "simultaneous one-sided 95\\% bounds from the task-cluster "
            "multiplier procedure; $p$-values are one-sided Fisher tests under "
            "the realised randomisation."
        ),
        header=("estimand", "estimate", "95\\% LB", "$p$"),
        rows=PRIMARY_ROWS,
    )


def resolution_table(package: SealedPackage | None) -> str:
    return _table(
        package,
        label="tab:resolution",
        caption=(
            "The measured resolution scale. $q_0$ and $r_{95}$ come from the "
            "two no-feedback replicates on the same tasks at the same trigger; "
            "neither is a confidence interval."
        ),
        header=("quantity", "value"),
        rows=RESOLUTION_ROWS,
    )


def environment_table(package: SealedPackage | None) -> str:
    return _table(
        package,
        label="tab:environments",
        caption=(
            "Per-environment estimates. The two environments carry equal weight "
            "in the primary estimator and are never pooled as one exchangeable "
            "population."
        ),
        header=("environment", "$\\Delta_{\\text{content}}$", "$\\Delta_{\\text{excess}}$", "$n$"),
        rows=ENVIRONMENT_ROWS,
    )


def figure_data(package: SealedPackage | None) -> dict[str, Any]:
    """Emit the machine-readable source for every figure.

    Figures are drawn from this file and never from ad-hoc values, so a figure
    can be regenerated and diffed against the paper.
    """

    keys = (
        "content.estimate",
        "content.lower_bound",
        "excess.estimate",
        "excess.lower_bound",
        "sham_packet.estimate",
        "continuation.estimate",
        "resolution.q0",
        "resolution.r95",
        "resolution.delta_star",
    )
    return {
        "source": "sealed_package" if package else "unfilled_scaffold",
        "artifact_root_digest": package.artifact_root_digest if package else None,
        "verdict": package.verdict if package else None,
        "series": {key: (package.numbers.get(key) if package else None) for key in keys},
        "notes": (
            "Figure 1 plots the two co-primary estimates against the measured "
            "resolution floor r95 and the practical screen delta_star. An "
            "estimate below either line is not reportable as an effect."
        ),
    }


def claim_evidence_matrix(
    claims: Sequence[Mapping[str, Any]], package: SealedPackage | None
) -> str:
    """Render the claim--evidence matrix as a LaTeX longtable-free table."""

    lines = [
        "% GENERATED by pneuma_lab.placebo_paper.render -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering\\small",
        (
            "\\caption{Claim--evidence matrix. Every claim in the manuscript maps to "
            "the receipt that supports it. A claim with no receipt is not made.}"
        ),
        "\\label{tab:claim-evidence}",
        "\\begin{tabular}{llp{0.45\\linewidth}}",
        "\\toprule",
        "claim & receipt & statement \\\\",
        "\\midrule",
    ]
    for claim in claims:
        receipt = str(claim.get("receipt", ""))
        resolved = "---"
        if package and receipt:
            resolved = package.receipts.get(receipt, "MISSING")[:12] or "MISSING"
        elif receipt:
            resolved = UNFILLED
        statement = str(claim.get("text", "")).replace("&", "\\&")
        lines.append(
            f"\\texttt{{{claim.get('claim_id')}}} & \\texttt{{{resolved}}} & {statement} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def artifact_appendix(package: SealedPackage | None) -> str:
    """Render the artifact appendix from the package's receipt index."""

    lines = [
        "% GENERATED by pneuma_lab.placebo_paper.render -- do not edit by hand.",
        "\\section{Artifact appendix}",
        "\\label{app:artifacts}",
        "",
    ]
    if package is None:
        lines.extend(
            [
                (
                    "No sealed evidence package has been admitted. This appendix is "
                    "an unfilled scaffold and the paper preflight blocks while it "
                    "remains so."
                ),
                "",
                UNFILLED,
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            (
                f"Verdict: \\texttt{{{package.verdict}}}. "
                f"Artifact root: \\texttt{{{package.artifact_root_digest[:16]}\\ldots}}"
            ),
            "",
            "\\begin{tabular}{ll}",
            "\\toprule",
            "receipt & digest \\\\",
            "\\midrule",
        ]
    )
    for name in sorted(package.receipts):
        lines.append(f"\\texttt{{{name}}} & \\texttt{{{package.receipts[name][:16]}\\ldots}} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    return "\n".join(lines)


def write_assets(
    out_dir: Path,
    package: SealedPackage | None,
    claims: Sequence[Mapping[str, Any]] = (),
) -> dict[str, int]:
    """Write every generated asset, returning byte counts per file."""

    out_dir.mkdir(parents=True, exist_ok=True)
    assets = {
        "table-primary.tex": primary_table(package),
        "table-resolution.tex": resolution_table(package),
        "table-environments.tex": environment_table(package),
        "table-claim-evidence.tex": claim_evidence_matrix(claims, package),
        "appendix-artifacts.tex": artifact_appendix(package),
        "figure-data.json": json.dumps(figure_data(package), indent=4, sort_keys=True) + "\n",
    }
    written: dict[str, int] = {}
    for name, text in assets.items():
        (out_dir / name).write_text(text, encoding="utf-8")
        written[name] = len(text.encode("utf-8"))
    return written
