"""Earned control-authority ladder (5-tier extension of F6 autonomy).

Where ``autonomy.py`` grants a 3-tier veto ceiling (cosmetic < soft < hard),
this module extends the ladder to five graded tiers of control authority —
cosmetic < soft < vote < hold < veto — and resolves the *effective* authority
as the minimum over every independent cap (conviction band, earned track-record
ceiling, per-domain ceiling, operator ceiling, safety ceiling, verifier ceiling)
and a final hard clamp to ``config.HN_AUTHORITY_MAX``.

The system PROPOSES; authority is EARNED and multiply-capped; humans and safety
gates can always clamp it down.  This module is pure: no I/O, no Ollama, no
Discord.  Config thresholds are read defensively via ``getattr`` so the module
loads even before the parallel HN_THETA_* flags land.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    band(conviction: float) -> str  -- Raw authority tier for *conviction* from the HN_THETA_* thresholds.
    earned_ceiling(track: dict[str, Any]) -> str  -- 5-tier earned authority ceiling from a ``track_record``-shaped dict.
    cap(tier: str, ceil: str) -> str  -- Return ``min(tier, ceil)`` on the ``TIERS`` ordering.
    resolve(conviction: float, track: dict[str, Any], domain_ceiling: str, operator_ceiling: str, safety_ceiling: str, verifier_ceiling: str) -> str  -- Effective control authority = ``min`` over every cap, then a hard clamp.
DEPENDS-ON: config
SIDE-EFFECTS: none (pure)
RUN/TEST: python -m pytest tests/human_nature/test_authority.py
"""
from __future__ import annotations

from typing import Any

import config

# Ordered tiers: index 0 = weakest, index 4 = strongest.
TIERS: tuple[str, ...] = ("cosmetic", "soft", "vote", "hold", "veto")

# Earned-ceiling volume gates and rate thresholds (F6 "teeth = proven reliability").
MIN_SAMPLES: int = 5    # cold-start floor: below this the track record has no teeth
VOTE_MIN_TOTAL: int = 20
VETO_MIN_TOTAL: int = 40
RATE_SOFT: float = 0.65
RATE_VOTE: float = 0.75
RATE_HOLD: float = 0.85
RATE_VETO: float = 0.95


def _theta(name: str, default: float) -> float:
    """Read a HN_THETA_* threshold from config, falling back to *default*."""
    return float(getattr(config, name, default))


def band(conviction: float) -> str:
    """Raw authority tier for *conviction* from the HN_THETA_* thresholds.

    cosmetic if c < HN_THETA_SOFT; soft if < HN_THETA_VOTE; vote if < HN_THETA_HOLD;
    hold if < HN_THETA_VETO; else veto.
    """
    c = float(conviction)
    if c < _theta("HN_THETA_SOFT", 0.60):
        return "cosmetic"
    if c < _theta("HN_THETA_VOTE", 0.72):
        return "soft"
    if c < _theta("HN_THETA_HOLD", 0.85):
        return "vote"
    if c < _theta("HN_THETA_VETO", 0.95):
        return "hold"
    return "veto"


def earned_ceiling(track: dict[str, Any]) -> str:
    """5-tier earned authority ceiling from a ``track_record``-shaped dict.

    Args:
        track: dict with keys ``rate`` (float in [0,1]) and ``total`` (int).

    Returns:
        One of ``TIERS``.  Cold start (``total < MIN_SAMPLES``) floors at cosmetic.
    """
    total = int(track.get("total", 0))
    rate = float(track.get("rate", 0.0))

    if total < MIN_SAMPLES:
        return "cosmetic"
    if rate >= RATE_VETO and total >= VETO_MIN_TOTAL:
        return "veto"
    if rate >= RATE_HOLD and total >= VOTE_MIN_TOTAL:
        return "hold"
    if rate >= RATE_VOTE and total >= VOTE_MIN_TOTAL:
        return "vote"
    if rate >= RATE_SOFT:
        return "soft"
    return "cosmetic"


def cap(tier: str, ceil: str) -> str:
    """Return ``min(tier, ceil)`` on the ``TIERS`` ordering.

    Unknown tiers are treated as the weakest (index 0).
    """
    tier_idx = TIERS.index(tier) if tier in TIERS else 0
    ceil_idx = TIERS.index(ceil) if ceil in TIERS else 0
    return TIERS[min(tier_idx, ceil_idx)]


def resolve(
    conviction: float,
    track: dict[str, Any],
    domain_ceiling: str,
    operator_ceiling: str,
    safety_ceiling: str,
    verifier_ceiling: str,
) -> str:
    """Effective control authority = ``min`` over every cap, then a hard clamp.

    Chains the conviction band through the earned, domain, operator, safety, and
    verifier ceilings (each can only lower the tier), then clamps the result to
    ``config.HN_AUTHORITY_MAX`` (default ``"hold"``) as a final hard cap.
    """
    tier = band(conviction)
    tier = cap(tier, earned_ceiling(track))
    tier = cap(tier, domain_ceiling)
    tier = cap(tier, operator_ceiling)
    tier = cap(tier, safety_ceiling)
    tier = cap(tier, verifier_ceiling)
    hard_max = str(getattr(config, "HN_AUTHORITY_MAX", "hold"))
    return cap(tier, hard_max)
