"""InstinctSignal — structured output of the streaming instinct engine.

A pure dataclass describing one motif match: what matched, how confident,
how severe if ignored, and what the engine recommends the run do about it.
Validation happens in __post_init__ so callers get a fast, explicit failure
on malformed enum fields instead of a silent bad state downstream.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    InstinctSignal  -- One streaming-instinct-engine match, with confidence/severity and a recommendation.
    from_dict(d: dict) -> 'InstinctSignal'  -- Reconstruct an InstinctSignal from its to_dict() output.
DEPENDS-ON: (stdlib only)
SIDE-EFFECTS: none (pure)
RUN/TEST: python -m pytest tests/human_nature/test_instinct_signal.py
"""
from __future__ import annotations

from dataclasses import dataclass, field

MATCH_TYPES = frozenset({"prefix", "exact", "near_duplicate", "anomaly"})
RECOMMENDED_ACTIONS = frozenset({
    "pause", "simplify", "deepen_verification", "force_replan",
    "reduce_diff", "switch_strategy", "continue_fast_path",
})
AUTHORITY_REQUESTS = frozenset({"soft", "vote", "hold"})


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, float(value)))


@dataclass
class InstinctSignal:
    """One streaming-instinct-engine match, with confidence/severity and a recommendation."""
    motif_id: str
    match_type: str
    confidence: float
    severity: float
    expected_loss_if_ignored: float
    recommended_action: str
    authority_request: str
    evidence_events: list = field(default_factory=list)
    matched_history_refs: list = field(default_factory=list)

    def __post_init__(self) -> None:
        if self.match_type not in MATCH_TYPES:
            raise ValueError(f"invalid match_type: {self.match_type!r}")
        if self.recommended_action not in RECOMMENDED_ACTIONS:
            raise ValueError(f"invalid recommended_action: {self.recommended_action!r}")
        if self.authority_request not in AUTHORITY_REQUESTS:
            raise ValueError(f"invalid authority_request: {self.authority_request!r}")
        self.confidence = _clamp01(self.confidence)
        self.severity = _clamp01(self.severity)

    def to_dict(self) -> dict:
        return {
            "motif_id": self.motif_id,
            "match_type": self.match_type,
            "confidence": self.confidence,
            "severity": self.severity,
            "expected_loss_if_ignored": self.expected_loss_if_ignored,
            "recommended_action": self.recommended_action,
            "authority_request": self.authority_request,
            "evidence_events": list(self.evidence_events),
            "matched_history_refs": list(self.matched_history_refs),
        }


def from_dict(d: dict) -> "InstinctSignal":
    """Reconstruct an InstinctSignal from its to_dict() output."""
    return InstinctSignal(
        motif_id=d["motif_id"],
        match_type=d["match_type"],
        confidence=d["confidence"],
        severity=d["severity"],
        expected_loss_if_ignored=d["expected_loss_if_ignored"],
        recommended_action=d["recommended_action"],
        authority_request=d["authority_request"],
        evidence_events=list(d.get("evidence_events", [])),
        matched_history_refs=list(d.get("matched_history_refs", [])),
    )
