"""Mood — the slow, persistent affective homeostat (long-horizon, cross-run).

Distinct from emotions.py's PAD appraisal (fast, per-event) and self_state's
`affect` (per-run reading): mood is the low-pass-filtered trace of run outcomes
that decays toward a personality setpoint across runs, and mood-congruently
biases ambiguous inputs the way `emotions.bias_appraisal` biases PAD valence.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    new_mood() -> dict[str, float]
    blend_outcome(mood: dict[str, Any], run_valence: float, run_arousal: float, weight: float=0.3) -> dict[str, float]  -- Exponential moving average of `mood` toward this run's outcome signal.
    decay(mood: dict[str, Any], setpoint: dict[str, Any], rate: float) -> dict[str, float]  -- Move `mood` toward `setpoint` by `rate` (0=no change, 1=snap to setpoint).
    congruent_bias(valence: float, mood: dict[str, Any], strength: float=0.5) -> float  -- Apply mood-congruent bias to an ambiguous input valence.
DEPENDS-ON: config
SIDE-EFFECTS: none (pure)
RUN/TEST: python -m pytest tests/human_nature/test_mood.py
"""
from __future__ import annotations

from typing import Any

import config

DEFAULT_DECAY_RATE = getattr(config, "HN_MOOD_DECAY", 0.15)


def _clamp(value: float) -> float:
    return max(-1.0, min(1.0, float(value)))


def new_mood() -> dict[str, float]:
    return {"valence": 0.0, "arousal": 0.0}


def blend_outcome(
    mood: dict[str, Any],
    run_valence: float,
    run_arousal: float,
    weight: float = 0.3,
) -> dict[str, float]:
    """Exponential moving average of `mood` toward this run's outcome signal.

    new = (1 - weight) * mood + weight * run_signal, clamped to [-1, 1].
    Not mutated: returns a new dict.
    """
    weight = max(0.0, min(1.0, float(weight)))
    retention = 1.0 - weight
    new_valence = retention * float(mood.get("valence", 0.0)) + weight * float(run_valence)
    new_arousal = retention * float(mood.get("arousal", 0.0)) + weight * float(run_arousal)
    return {"valence": _clamp(new_valence), "arousal": _clamp(new_arousal)}


def decay(
    mood: dict[str, Any],
    setpoint: dict[str, Any],
    rate: float,
) -> dict[str, float]:
    """Move `mood` toward `setpoint` by `rate` (0=no change, 1=snap to setpoint).

    Pure; clamped to [-1, 1]. Not mutated: returns a new dict.
    """
    rate = max(0.0, min(1.0, float(rate)))
    new_valence = float(mood.get("valence", 0.0)) + rate * (
        float(setpoint.get("valence", 0.0)) - float(mood.get("valence", 0.0))
    )
    new_arousal = float(mood.get("arousal", 0.0)) + rate * (
        float(setpoint.get("arousal", 0.0)) - float(mood.get("arousal", 0.0))
    )
    return {"valence": _clamp(new_valence), "arousal": _clamp(new_arousal)}


def congruent_bias(valence: float, mood: dict[str, Any], strength: float = 0.5) -> float:
    """Apply mood-congruent bias to an ambiguous input valence.

    Mirrors emotions.bias_appraisal: when mood valence is negative, a
    low-magnitude (ambiguous) input valence is pulled toward negative;
    high-magnitude (unambiguous, strong) inputs are protected from being
    flipped. Positive/neutral mood applies no shift.

    Args:
        valence:  Ambiguous input valence in [-1, 1]; not mutated (a scalar).
        mood:     Mood dict; not mutated.
        strength: Scale of the maximum shift (0 = no bias, 1 = full bias).

    Returns:
        New valence in [-1, 1].
    """
    mood_valence = float(mood.get("valence", 0.0))
    if mood_valence >= 0.0:
        return _clamp(valence)
    old_v = float(valence)
    # Ambiguity = how far from a strong, clear signal (1.0 when v=0, 0.0 when |v|=1)
    ambiguity = 1.0 - abs(old_v)
    shift = mood_valence * ambiguity * float(strength)
    return _clamp(old_v + shift)
