"""Operator / safety / verifier-invariance authority caps feeding authority.resolve.

This module supplies the *ceilings* that bound how much authority any faculty may
exert over an action.  Ceilings are named tiers from the shared `TIERS` ladder
(cosmetic < soft < vote < hold < veto).  Three independent caps are computed and
the strictest (lowest) one wins upstream in `authority.resolve`:

    * operator_ceiling  -- constitutional cap: how much the operator/charter grants a
    given (faculty, domain).  Defaults to the config ceiling; a charter may only
    *lower* it, never raise it.
    * safety_ceiling    -- hard safety cap keyed by domain (unknown -> cosmetic).
    * verifier_invariance_ceiling -- keeps the verifier verdict untouchable: any
    action that would read or alter a verdict is capped at cosmetic; additive-only
    verification actions cap at hold; everything else at veto.

Pure module: no I/O, no Ollama, config read via getattr fallback only.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    domain_ceiling(domain: str) -> str  -- Return the structural authority ceiling for an opinion *domain*.
    operator_ceiling(faculty: str, domain: str, charter: dict | None=None) -> str  -- Return the constitutional ceiling the operator grants (faculty, domain).
    safety_ceiling(domain: str) -> str  -- Return the hard safety ceiling for *domain*.
    verifier_invariance_ceiling(action: str) -> str  -- Return the ceiling that keeps the verifier verdict untouchable.
DEPENDS-ON: config
SIDE-EFFECTS: none (pure)
RUN/TEST: python -m pytest tests/human_nature/test_operator_authority.py
"""
from __future__ import annotations

import config

TIERS: tuple[str, ...] = ("cosmetic", "soft", "vote", "hold", "veto")

# Structural veto-teeth per opinion domain.  D1 tactics / D2 scope are execution
# and spec decisions the system may hard-block; D3 goal / D4 self are the user's
# sovereign territory (argue via vote, never veto); unknown domains earn nothing.
_DOMAIN_CEILING: dict[str, str] = {
    "tactics": "veto",
    "scope": "veto",
    "goal": "vote",
    "self": "vote",
}

# Hard safety caps keyed by domain.  Anything absent from this map that is *not*
# the wildcard default is treated as an unknown domain (cosmetic).
_SAFETY_HARD_CAP: dict[str, str] = {}

# Verifier-invariance: reading or altering a verdict is never permitted above
# cosmetic — the verifier verdict is the untouchable source of truth.
_VERDICT_ACTIONS: frozenset[str] = frozenset({
    "read_verdict",
    "alter_verdict",
    "set_verdict",
    "override_verdict",
    "clear_verdict",
    "edit_verdict",
    "delete_verdict",
    "mutate_verdict",
})

# Additive-only verification actions: they may *deepen* verification but never
# touch an existing verdict, so they cap at hold (strong, still not veto).
_ADDITIVE_VERIFICATION_ACTIONS: frozenset[str] = frozenset({
    "deepen_verification",
    "request_adversarial_pass",
})


def _lower_of(a: str, b: str) -> str:
    """Return the stricter (lower-index) of two tiers."""
    return TIERS[min(TIERS.index(a), TIERS.index(b))]


def domain_ceiling(domain: str) -> str:
    """Return the structural authority ceiling for an opinion *domain*.

    tactics/scope -> "veto"; goal/self -> "vote"; unknown -> "cosmetic".
    """
    return _DOMAIN_CEILING.get(domain, "cosmetic")


def operator_ceiling(
    faculty: str,
    domain: str,
    charter: dict | None = None,
) -> str:
    """Return the constitutional ceiling the operator grants (faculty, domain).

    Starts from the config default (``HN_OPERATOR_CEILING``, "veto" if unset).
    A charter may *lower* the ceiling for a specific ``"{faculty}:{domain}"`` key
    via ``charter["ceilings"]`` but may never raise it above the default.
    """
    default = getattr(config, "HN_OPERATOR_CEILING", "veto")
    if not charter:
        return default
    ceilings = charter.get("ceilings") or {}
    override = ceilings.get(f"{faculty}:{domain}")
    if override is None or override not in TIERS:
        return default
    # Charter can only tighten (lower) the cap, never loosen it.
    return _lower_of(default, override)


def safety_ceiling(domain: str) -> str:
    """Return the hard safety ceiling for *domain*.

    A domain present in ``_SAFETY_HARD_CAP`` uses its mapped cap; an unknown
    domain caps at "cosmetic"; the wildcard default (empty domain) is "veto".
    """
    if domain in _SAFETY_HARD_CAP:
        return _SAFETY_HARD_CAP[domain]
    if not domain:
        return "veto"
    return "cosmetic"


def verifier_invariance_ceiling(action: str) -> str:
    """Return the ceiling that keeps the verifier verdict untouchable.

    Reading or altering a verdict -> "cosmetic" (the verdict is inviolable);
    additive-only verification actions -> "hold"; anything else -> "veto".
    """
    if action in _VERDICT_ACTIONS:
        return "cosmetic"
    if action in _ADDITIVE_VERIFICATION_ACTIONS:
        return "hold"
    return "veto"
