"""Prototype projection — continuous affect manifold → discrete emotion labels.

The affect manifold (affect_manifold.py) is a continuous point in a 9-axis
space.  This module projects that point onto a small set of discrete emotion
prototype anchors via radial-basis (RBF) activation, yielding both a soft
mixture (mixture) and a single dominant label (dominant).

dominant() applies HYSTERESIS so the label does not flicker on small manifold
jitter: an already-active label is held while its activation stays above a
release threshold (theta_off), and is only replaced when a *different*
non-neutral prototype clears a higher switch-on threshold (theta_on) and beats
it.  "neutral" is the fallback when no prototype is active; it never triggers a
switch away from an active emotion (that is the whole point of hysteresis).

Pure: no I/O, no globals mutated.  Anchors are subsets of AXES; any axis a
prototype omits is treated as 0.0, and the manifold likewise defaults to 0.0.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    mixture(a: dict) -> dict[str, float]  -- RBF activation per prototype, normalized so the values sum to 1.0.
    dominant(a: dict, prev: str | None=None, theta_on: float=0.5, theta_off: float=0.35) -> str  -- Dominant emotion label for manifold ``a`` with flicker-resistant hysteresis.
DEPENDS-ON: (stdlib only)
SIDE-EFFECTS: none (pure)
RUN/TEST: python -m pytest tests/human_nature/test_prototypes.py
"""
from __future__ import annotations

import math

AXES = (
    "valence",
    "arousal",
    "dominance",
    "certainty",
    "novelty",
    "agency",
    "tension",
    "social_exposure",
    "cognitive_load",
)

# Emotion prototype anchors.  Each is a subset of AXES; omitted axes = 0.0.
PROTOTYPES: dict[str, dict] = {
    "frustration": {"valence": -0.6, "arousal": 0.6, "tension": 0.6},
    "anxiety": {"valence": -0.5, "arousal": 0.4, "certainty": -0.5, "tension": 0.5},
    "curiosity": {"valence": 0.4, "arousal": 0.3, "novelty": 0.7},
    "boredom": {"arousal": -0.5, "novelty": -0.5},
    "satisfaction": {"valence": 0.7, "arousal": 0.2, "dominance": 0.4},
    "neutral": {},
}

# RBF width.  2*sigma^2 is the denominator of the Gaussian kernel.
_SIGMA = 0.6
_TWO_SIGMA_SQ = 2.0 * _SIGMA * _SIGMA


def _dist2(a: dict, anchor: dict) -> float:
    """Squared Euclidean distance over all AXES (missing components = 0.0)."""
    total = 0.0
    for ax in AXES:
        d = float(a.get(ax, 0.0)) - float(anchor.get(ax, 0.0))
        total += d * d
    return total


def _activations(a: dict) -> dict[str, float]:
    """Raw (un-normalized) RBF activation in (0, 1] for each prototype.

    activation_k = exp(-dist2(a, anchor_k) / (2*sigma^2)); equals 1.0 exactly
    when the manifold sits on the anchor.  These raw values (not the normalized
    mixture) are what the hysteresis thresholds in dominant() compare against.
    """
    return {
        label: math.exp(-_dist2(a, anchor) / _TWO_SIGMA_SQ)
        for label, anchor in PROTOTYPES.items()
    }


def mixture(a: dict) -> dict[str, float]:
    """RBF activation per prototype, normalized so the values sum to 1.0.

    Args:
        a: An affect manifold dict (any subset of AXES; missing axis = 0.0).

    Returns:
        {label: weight} over all PROTOTYPES, weights >= 0 summing to 1.0.
    """
    raw = _activations(a)
    total = sum(raw.values())
    if total <= 0.0:  # unreachable (exp > 0), but keep normalization safe
        n = len(raw)
        return {label: 1.0 / n for label in raw}
    return {label: value / total for label, value in raw.items()}


def dominant(
    a: dict,
    prev: str | None = None,
    theta_on: float = 0.5,
    theta_off: float = 0.35,
) -> str:
    """Dominant emotion label for manifold ``a`` with flicker-resistant hysteresis.

    Selection uses the raw RBF activations (see _activations): 1.0 at an anchor,
    decaying with distance.  "neutral" is the fallback and is never a switch
    target — it cannot override an active emotion.

    Rules:
        * If ``prev`` is an active (non-neutral) label whose activation is still
        >= ``theta_off``, KEEP it, UNLESS a different non-neutral prototype both
        clears ``theta_on`` and beats prev's activation.
        * Otherwise pick the strongest non-neutral prototype if it clears
        ``theta_on``; failing that, return "neutral".

    Args:
        a:         Affect manifold dict (missing axis = 0.0).
        prev:      Previously emitted label, for hysteresis; None = fresh pick.
        theta_on:  Switch-ON gate; a new label must exceed this to take over.
        theta_off: Release gate; prev is held while its activation stays above.

    Returns:
        One label from PROTOTYPES (possibly "neutral").
    """
    raw = _activations(a)
    non_neutral = {k: v for k, v in raw.items() if k != "neutral"}
    top_label = max(non_neutral, key=non_neutral.get)
    top_val = non_neutral[top_label]

    if prev is not None and prev != "neutral":
        prev_val = raw.get(prev, 0.0)
        if prev_val >= theta_off:
            if top_label != prev and top_val >= theta_on and top_val > prev_val:
                return top_label
            return prev

    if top_val >= theta_on:
        return top_label
    return "neutral"
