"""Run event log — a discrete event stream over one 9to5 run.

A run is modeled as an ordered list of small event dicts. A later "instinct"
module pattern-matches over the type sequence to recognize risky shapes
(e.g. scope creep, skipped verification, retry loops) without needing to
re-derive them from raw state. This module only records and replays the
stream; it does not interpret it.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    new_event_log() -> list
    record_event(log: list, etype: str, **fields: Any) -> None
    event_sequence(log: list) -> list[str]
DEPENDS-ON: (stdlib only)
SIDE-EFFECTS: mutates the passed-in log list in place
RUN/TEST: python -m pytest tests/human_nature/test_run_events.py
"""
from __future__ import annotations

from typing import Any

EVENT_TYPES: frozenset[str] = frozenset(
    {
        "SUBTASK_STARTED",
        "PLAN_SCOPE_EXPANDED",
        "PLAN_TOO_BROAD",
        "PATCH_LARGE",
        "PATCH_SIZE_SPIKE",
        "TESTS_SKIPPED",
        "TESTS_NOT_YET_RUN",
        "VERIFIER_WARNING",
        "RETRY_SAME_STRATEGY",
        "CONFIDENCE_HIGH",
        "REGRESSION_FOUND",
        "TOOL_TIMEOUT",
        "OPERATOR_INTERRUPTION",
        "DIFF_EXPANDING",
        "NO_PROGRESS_LOOP",
    }
)


def new_event_log() -> list:
    return []


def record_event(log: list, etype: str, **fields: Any) -> None:
    if etype not in EVENT_TYPES:
        return
    log.append({"type": etype, "seq": len(log), "fields": fields})


def event_sequence(log: list) -> list[str]:
    return [event["type"] for event in log]
