"""SelfState — the unified interior of the human-nature layer (a serializable dict).

The interior is a plain dict so it round-trips through TaskState.meta['self_state']
with no new serialization machinery. Faculties are pure functions over this dict;
this module owns its shape, defaults, and the basic competence/affect updates.

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    new_self_state() -> dict[str, Any]
    migrate(ss: dict[str, Any]) -> dict[str, Any]
    get_competence(ss: dict[str, Any], domain: str) -> dict[str, Any]
    observe_competence(ss: dict[str, Any], domain: str, success: bool) -> None
    set_affect(ss: dict[str, Any], valence: float, arousal: float, control: float) -> None
DEPENDS-ON: (stdlib only)
SIDE-EFFECTS: mutates the passed-in dict in place
RUN/TEST: python -m pytest tests/human_nature/test_self_state.py
"""
from __future__ import annotations

from typing import Any

SCHEMA_VERSION = 2

_AFFECT_MANIFOLD_AXES = (
    "valence", "arousal", "dominance", "certainty", "novelty",
    "agency", "tension", "social_exposure", "cognitive_load",
)


def new_self_state() -> dict[str, Any]:
    return {
        "schema": SCHEMA_VERSION,
        "competence": {},      # domain -> {"p": float, "n": int}
        "affect": {"valence": 0.0, "arousal": 0.0, "control": 0.0},
        "morale": 0.0,         # slow homeostat in [-1, 1]
        "convictions": [],     # crystallized stable stances
        "open_stances": [],    # live opinions this run
        "dissonance": 0.0,
        "affect_manifold": {axis: 0.0 for axis in _AFFECT_MANIFOLD_AXES},
        "drives": {},           # filled by a later phase
        "personality_ref": None,
        "mood": {"valence": 0.0, "arousal": 0.0},
        "scars_ref": None,
    }


def migrate(ss: dict[str, Any]) -> dict[str, Any]:
    if ss.get("schema", 1) < 2:
        defaults = new_self_state()
        for key in ("affect_manifold", "drives", "personality_ref", "mood", "scars_ref"):
            ss.setdefault(key, defaults[key])
        ss["schema"] = 2
    return ss


def get_competence(ss: dict[str, Any], domain: str) -> dict[str, Any]:
    return ss["competence"].get(domain, {"p": 0.5, "n": 0})


def observe_competence(ss: dict[str, Any], domain: str, success: bool) -> None:
    cur = get_competence(ss, domain)
    n = cur["n"] + 1
    p = cur["p"] + ((1.0 if success else 0.0) - cur["p"]) / n
    ss["competence"][domain] = {"p": p, "n": n}


def set_affect(ss: dict[str, Any], valence: float, arousal: float, control: float) -> None:
    ss["affect"] = {
        "valence": float(valence),
        "arousal": float(arousal),
        "control": float(control),
    }
