"""Global Workspace — the GWT competition/broadcast loop (Baars, Dehaene).

Specialist processes compete for the workspace; the winning content is broadcast
to all specialists and becomes the system's momentary "conscious content." Awareness
equals global availability. All specialists are injected callables — no Ollama, no
Discord, no hidden state (closed API, F10).

@AI-MAP v1  (generated by tools/repo_map.py -- edit SIDE-EFFECTS only, then regenerate)
EXPORTS:
    Workspace  -- Global Workspace: specialists compete, winner is broadcast.
    salience(item: dict, weights: dict | None=None) -> float  -- Weighted sum over the 10 named salience terms
DEPENDS-ON: (stdlib only)
SIDE-EFFECTS: none (pure; broadcast may call specialist.on_broadcast callbacks)
RUN/TEST: python -m pytest tests/human_nature/test_workspace.py
"""
from __future__ import annotations

from typing import Any, Callable, Optional


class Workspace:
    """Global Workspace: specialists compete, winner is broadcast.

    Each specialist is a callable ``(state) -> {"content": str, "salience": float}``.
    Ties in salience are broken by registration order (first-registered wins).
    """

    def __init__(self) -> None:
        # Preserve insertion order for deterministic tie-breaking.
        self._specialists: list[tuple[str, Callable]] = []

    def register(self, name: str, specialist: Callable) -> None:
        """Register a named specialist process."""
        self._specialists.append((name, specialist))

    def tick(self, state: Any) -> Optional[dict]:
        """Run all specialists on *state*; return the broadcast winner or None."""
        if not self._specialists:
            return None

        results = [
            (name, spec(state))
            for name, spec in self._specialists
        ]

        # Pick max salience; ties broken by list order (first wins, via stable max).
        winner_name, winner_out = _select_winner(results)

        losers = [name for name, _ in results if name != winner_name]
        return {
            "winner": winner_name,
            "content": winner_out["content"],
            "salience": winner_out["salience"],
            "losers": losers,
        }

    def broadcast(self, winner: dict) -> None:
        """Notify all specialists that define an ``on_broadcast`` method."""
        for _name, spec in self._specialists:
            callback = getattr(spec, "on_broadcast", None)
            if callable(callback):
                try:
                    callback(winner)
                except Exception:
                    pass  # defensive: never let a broken callback silence the loop


SALIENCE_WEIGHTS = {
    "conviction": 1.0,
    "expected_loss": 1.0,
    "uncertainty": 0.7,
    "novelty": 0.5,
    "scar_tissue": 0.9,
    "unresolved_tension": 0.6,
    "recency": 0.4,
    "operator_priority": 0.8,
    "risk": 0.7,
    "competence_gap": 0.6,
}


def salience(item: dict, weights: dict | None = None) -> float:
    """Weighted sum over the 10 named salience terms; pure, may exceed 1.0.

    Each term is read from *item* via ``.get(name, 0.0)``. *weights* defaults to
    ``SALIENCE_WEIGHTS``; when provided, it is merged over the defaults (caller
    override wins per-key, unspecified keys keep their default weight).
    """
    merged_weights = {**SALIENCE_WEIGHTS, **(weights or {})}
    return sum(
        float(item.get(term, 0.0)) * weight
        for term, weight in merged_weights.items()
    )


def _select_winner(results: list[tuple[str, dict]]) -> tuple[str, dict]:
    """Return the (name, output) with the highest salience (first-registered on tie)."""
    best_name, best_out = results[0]
    best_sal = float(best_out["salience"])
    for name, out in results[1:]:
        sal = float(out["salience"])
        if sal > best_sal:
            best_sal = sal
            best_name = name
            best_out = out
    return best_name, best_out
