"""Self-contained HTML "mind monitor" generated from a voice stream.

Pure and byte-deterministic: it injects a sorted-key JSON island into one inline
HTML/CSS/JS document (no external requests — safe to share and CSP-compatible).
The page renders the thought stream tick-by-tick from the embedded data; the
runtime reveal animation does not affect the generated bytes.
"""

from __future__ import annotations

import json
from pathlib import Path


def monitor_payload(stream: dict) -> dict:
    """Deterministic view model: per-tick rendered lines with credit + receipts."""
    by_tick: dict[int, list[dict]] = {}
    for atom, rendered in zip(stream["atoms"], stream["rendered"]):
        by_tick.setdefault(int(atom["tick"]), []).append(
            {
                "type": atom["type"],
                "credit_status": atom["credit_status"],
                "text": rendered.get("text_voiced") or rendered["text_deterministic"],
                "voice_status": rendered.get("voice_status", "deterministic_only"),
                "receipts": atom.get("receipts", []),
            }
        )
    ticks = [{"tick": t, "lines": by_tick[t]} for t in sorted(by_tick)]
    sidecar = stream.get("sidecar", {})
    return {
        "subject": stream["subject"],
        "mode": stream["mode"],
        "evidence_level": stream["evidence_level"],
        "run_id": stream["run_id"],
        "indicator_family_status": sidecar.get("indicator_family_status", {}),
        "ticks": ticks,
    }


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pneuma Voice — __SUBJECT__</title>
<style>
:root{
  --bg:#0a0e14; --panel:#111823; --edge:#1e2a3a; --ink:#c9d6e5; --dim:#6b7c93;
  --evidenced:#3b82f6; --backed:#22c55e; --arch:#f59e0b; --absent:#64748b; --accent:#8b5cf6;
}
*{box-sizing:border-box}
body{margin:0;background:radial-gradient(1200px 600px at 50% -10%,#131c2b,var(--bg));
  color:var(--ink);font:15px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
header{position:sticky;top:0;z-index:5;padding:18px 22px;background:rgba(10,14,20,.86);
  backdrop-filter:blur(6px);border-bottom:1px solid var(--edge);display:flex;align-items:center;gap:16px;flex-wrap:wrap}
h1{font-size:15px;margin:0;letter-spacing:.14em;text-transform:uppercase;color:#e8eef6}
h1 small{color:var(--dim);letter-spacing:.06em;text-transform:none}
.badge{margin-left:auto;padding:6px 14px;border-radius:999px;font-weight:700;letter-spacing:.06em;
  border:1px solid var(--accent);color:#dcd2ff;box-shadow:0 0 22px rgba(139,92,246,.35)}
.families{display:flex;gap:6px;flex-wrap:wrap}
.dot{display:inline-flex;align-items:center;gap:5px;font-size:11px;color:var(--dim);
  border:1px solid var(--edge);padding:2px 8px;border-radius:999px}
.dot i{width:8px;height:8px;border-radius:50%;background:var(--absent);display:inline-block}
.dot.evidenced i{background:var(--evidenced)} .dot.intervention_backed i{background:var(--backed)}
.dot.architecture_only i{background:var(--arch)} .dot.attempted i{background:var(--arch)}
main{max-width:900px;margin:0 auto;padding:26px 22px 120px}
.controls{display:flex;gap:10px;margin:6px 0 22px}
button{background:var(--panel);color:var(--ink);border:1px solid var(--edge);border-radius:8px;
  padding:8px 14px;cursor:pointer;font:inherit}
button:hover{border-color:var(--accent)}
.tick{margin:0 0 26px;opacity:0;transform:translateY(8px);transition:opacity .5s,transform .5s}
.tick.show{opacity:1;transform:none}
.tick h2{font-size:12px;color:var(--dim);letter-spacing:.16em;text-transform:uppercase;margin:0 0 10px;
  border-bottom:1px dashed var(--edge);padding-bottom:6px}
.line{position:relative;padding:10px 12px 10px 16px;margin:8px 0;background:var(--panel);
  border:1px solid var(--edge);border-left:3px solid var(--absent);border-radius:8px}
.line.evidenced{border-left-color:var(--evidenced)} .line.intervention_backed{border-left-color:var(--backed)}
.line.architecture_only{border-left-color:var(--arch)} .line.attempted{border-left-color:var(--arch)}
.chip{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim);margin-right:8px}
.chip b{color:var(--ink)}
.voiced{color:#a7b6c9;font-style:italic}
.rtoggle{cursor:pointer;color:var(--dim);font-size:11px;user-select:none;margin-top:6px;display:inline-block}
.rtoggle:hover{color:var(--accent)}
.receipts{display:none;margin:8px 0 2px;padding:8px 10px;background:#0c121b;border:1px solid var(--edge);
  border-radius:6px;font-size:12px;color:var(--dim)}
.receipts.open{display:block}
.receipts div{white-space:pre-wrap}
.receipts span{color:#9fb3c8}
footer{max-width:900px;margin:0 auto;padding:0 22px 60px;color:var(--dim);font-size:12px}
</style>
</head>
<body>
<header>
  <h1>Pneuma Voice <small>· __SUBJECT__ · <span id="mode"></span></small></h1>
  <div class="families" id="families"></div>
  <div class="badge" id="badge"></div>
</header>
<main>
  <div class="controls">
    <button id="play">▶ Play</button>
    <button id="all">Show all</button>
  </div>
  <div id="stream"></div>
</main>
<footer>
  Grounded, receipt-bound thought stream. The evidence scorer never reads this prose;
  credit is a display label, not a claim. Click a line to see its receipts.
</footer>
<script id="thought-stream-data" type="application/json">__DATA__</script>
<script>
(function(){
  var data = JSON.parse(document.getElementById("thought-stream-data").textContent);
  document.getElementById("mode").textContent = data.mode;
  document.getElementById("badge").textContent = "Evidence level " + data.evidence_level;
  var fam = document.getElementById("families");
  Object.keys(data.indicator_family_status).sort().forEach(function(k){
    var s = data.indicator_family_status[k];
    var d = document.createElement("span");
    d.className = "dot " + s;
    d.innerHTML = "<i></i>" + k.replace(/_/g," ");
    d.title = k + ": " + s;
    fam.appendChild(d);
  });
  var stream = document.getElementById("stream");
  data.ticks.forEach(function(tk){
    var sec = document.createElement("section");
    sec.className = "tick";
    var h = document.createElement("h2");
    h.textContent = "Tick " + tk.tick;
    sec.appendChild(h);
    tk.lines.forEach(function(ln){
      var el = document.createElement("div");
      el.className = "line " + ln.credit_status;
      var head = document.createElement("div");
      head.innerHTML = '<span class="chip"><b>' + ln.type + '</b> · ' + ln.credit_status + '</span>';
      var txt = document.createElement("span");
      txt.textContent = ln.text;
      if(ln.voice_status === "voiced"){ txt.className = "voiced"; }
      head.appendChild(txt);
      el.appendChild(head);
      if(ln.receipts && ln.receipts.length){
        var tog = document.createElement("div");
        tog.className = "rtoggle";
        tog.textContent = "▸ receipts (" + ln.receipts.length + ")";
        var box = document.createElement("div");
        box.className = "receipts";
        ln.receipts.forEach(function(r){
          var row = document.createElement("div");
          var key = document.createElement("span");
          key.textContent = r.field_path;
          var v = (r.value === null || r.value === undefined) ? "—" : String(r.value);
          row.appendChild(key);
          row.appendChild(document.createTextNode(" = " + v));
          box.appendChild(row);
        });
        tog.addEventListener("click", function(){
          box.classList.toggle("open");
          tog.textContent = (box.classList.contains("open") ? "▾" : "▸") + " receipts (" + ln.receipts.length + ")";
        });
        el.appendChild(tog); el.appendChild(box);
      }
      sec.appendChild(el);
    });
    stream.appendChild(sec);
  });
  var sections = Array.prototype.slice.call(document.querySelectorAll(".tick"));
  function showAll(){ sections.forEach(function(s){ s.classList.add("show"); }); }
  function play(){
    sections.forEach(function(s){ s.classList.remove("show"); });
    var i = 0;
    (function step(){
      if(i >= sections.length) return;
      sections[i].classList.add("show");
      sections[i].scrollIntoView({behavior:"smooth", block:"center"});
      i++; setTimeout(step, 900);
    })();
  }
  document.getElementById("all").addEventListener("click", showAll);
  document.getElementById("play").addEventListener("click", play);
  showAll();
})();
</script>
</body>
</html>
"""


def render_html(stream: dict) -> str:
    """Render a self-contained, deterministic mind-monitor HTML document."""
    payload = monitor_payload(stream)
    data = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    data = data.replace("</", "<\\/")
    subject = str(stream["subject"])
    return _TEMPLATE.replace("__DATA__", data).replace("__SUBJECT__", subject)


def write_monitor(stream: dict, out_path: str | Path) -> None:
    """Write the mind-monitor HTML to ``out_path`` (deterministic)."""
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_html(stream), encoding="utf-8", newline="\n")


__all__ = ["monitor_payload", "render_html", "write_monitor"]
