"""Self-contained HTML "mind monitor" (v2) generated from a voice stream.

Pure and byte-deterministic in deterministic mode: it injects a sorted-key JSON
island (atoms + rendered + a per-tick internal-state panel) into one inline
HTML/CSS/JS document (no external requests — safe to share, CSP-compatible). The
page plays the thought stream tick-by-tick with a live internal-state panel and a
timeline scrubber. Runtime animation does not affect the generated bytes. When a
non-canonical voiced skin is attached, its text is shown but is NOT part of any
byte-determinism guarantee.
"""

from __future__ import annotations

import json
from pathlib import Path


def _tick_panel(lines: list[dict], evidence_level: int) -> dict:
    pressure = None
    winner = None
    salience: dict = {}
    dominant_affect = None
    scar_strength = None
    predicted_error = None
    credit_counts: dict = {}
    for ln in lines:
        credit_counts[ln["credit_status"]] = (
            credit_counts.get(ln["credit_status"], 0) + 1
        )
        for r in ln.get("receipts", []):
            fp, val = r.get("field_path", ""), r.get("value")
            if (
                fp.startswith("control_pressure.")
                and not fp.endswith("authority_tier")
                and isinstance(val, (int, float))
            ):
                pressure = float(val)
            elif fp == "workspace_broadcast.winning_faculty":
                winner = val
            elif fp.startswith("salience_scores.") and isinstance(val, (int, float)):
                salience[fp.split(".", 1)[1]] = float(val)
            elif (
                fp.startswith("shift.")
                and not fp.endswith(".from")
                and isinstance(val, (int, float))
            ):
                dominant_affect = {"dim": fp.split(".", 1)[1], "value": float(val)}
            elif fp == "psyche_state.derived_signals.scar_strength" and isinstance(
                val, (int, float)
            ):
                scar_strength = float(val)
            elif fp == "psyche_state.self_model.predicted_error" and isinstance(
                val, (int, float)
            ):
                predicted_error = float(val)
    return {
        "pressure": pressure,
        "winner": winner,
        "salience": salience,
        "dominant_affect": dominant_affect,
        "scar_strength": scar_strength,
        "predicted_error": predicted_error,
        "credit_counts": credit_counts,
        "evidence_level": evidence_level,
    }


def monitor_payload(stream: dict) -> dict:
    """Deterministic view model: per-tick rendered lines + internal-state panel."""
    by_tick: dict[int, list[dict]] = {}
    for atom, rendered in zip(stream["atoms"], stream["rendered"]):
        by_tick.setdefault(int(atom["tick"]), []).append(
            {
                "type": atom["type"],
                "credit_status": atom["credit_status"],
                "text": rendered.get("text_voiced") or rendered["text_deterministic"],
                "voice_status": rendered.get("voice_status", "deterministic_only"),
                "receipts": atom.get("receipts", []),
            }
        )
    ev = stream["evidence_level"]
    ticks = [
        {"tick": t, "lines": by_tick[t], "panel": _tick_panel(by_tick[t], ev)}
        for t in sorted(by_tick)
    ]
    sidecar = stream.get("sidecar", {})
    return {
        "subject": stream["subject"],
        "mode": stream["mode"],
        "evidence_level": ev,
        "run_id": stream["run_id"],
        "indicator_family_status": sidecar.get("indicator_family_status", {}),
        "ticks": ticks,
    }


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pneuma Voice — __SUBJECT__</title>
<style>
:root{
  --bg:#080b11; --panel:#0f1621; --panel2:#0c121b; --edge:#1e2a3a; --ink:#c9d6e5; --dim:#63748c;
  --evidenced:#3b82f6; --backed:#22c55e; --arch:#f59e0b; --absent:#5b6b82; --accent:#8b5cf6;
}
*{box-sizing:border-box}
body{margin:0;background:radial-gradient(1400px 700px at 50% -12%,#121b2b,var(--bg));
  color:var(--ink);font:14.5px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
header{position:sticky;top:0;z-index:6;padding:14px 20px;background:rgba(8,11,17,.9);
  backdrop-filter:blur(7px);border-bottom:1px solid var(--edge);display:flex;align-items:center;gap:14px;flex-wrap:wrap}
h1{font-size:14px;margin:0;letter-spacing:.16em;text-transform:uppercase;color:#eaf0f8}
h1 small{color:var(--dim);letter-spacing:.05em;text-transform:none}
.badge{margin-left:auto;padding:6px 14px;border-radius:999px;font-weight:700;letter-spacing:.05em;
  border:1px solid var(--accent);color:#e2d9ff;box-shadow:0 0 24px rgba(139,92,246,.4)}
.families{display:flex;gap:6px;flex-wrap:wrap}
.dot{display:inline-flex;align-items:center;gap:5px;font-size:10.5px;color:var(--dim);
  border:1px solid var(--edge);padding:2px 8px;border-radius:999px}
.dot i{width:8px;height:8px;border-radius:50%;background:var(--absent);display:inline-block}
.dot.evidenced i{background:var(--evidenced)} .dot.intervention_backed i{background:var(--backed)}
.dot.architecture_only i{background:var(--arch)} .dot.attempted i{background:var(--arch)}
.layout{display:grid;grid-template-columns:1fr 320px;gap:22px;max-width:1180px;margin:0 auto;padding:22px 20px 20px}
@media(max-width:820px){.layout{grid-template-columns:1fr}}
.tick{margin:0 0 22px;opacity:.35;transition:opacity .4s}
.tick.active{opacity:1}
.tick h2{font-size:11px;color:var(--dim);letter-spacing:.18em;text-transform:uppercase;margin:0 0 9px;
  border-bottom:1px dashed var(--edge);padding-bottom:6px}
.line{padding:9px 12px 9px 15px;margin:7px 0;background:var(--panel);border:1px solid var(--edge);
  border-left:3px solid var(--absent);border-radius:8px}
.line.evidenced{border-left-color:var(--evidenced)} .line.intervention_backed{border-left-color:var(--backed)}
.line.architecture_only{border-left-color:var(--arch)} .line.attempted{border-left-color:var(--arch)}
.chip{font-size:10px;letter-spacing:.07em;text-transform:uppercase;color:var(--dim);margin-right:8px}
.chip b{color:var(--ink)}
.tag{font-size:9.5px;color:var(--accent);border:1px solid var(--accent);border-radius:5px;padding:0 5px;margin-left:6px;opacity:.8}
.voiced{color:#b7c6da;font-style:italic}
.rtoggle{cursor:pointer;color:var(--dim);font-size:11px;user-select:none;margin-top:6px;display:inline-block}
.rtoggle:hover{color:var(--accent)}
.receipts{display:none;margin:8px 0 2px;padding:8px 10px;background:var(--panel2);border:1px solid var(--edge);
  border-radius:6px;font-size:12px;color:var(--dim)}
.receipts.open{display:block}
.receipts div{white-space:pre-wrap}
.receipts span{color:#9fb3c8}
aside{position:sticky;top:70px;align-self:start;background:var(--panel);border:1px solid var(--edge);
  border-radius:12px;padding:16px;height:fit-content}
aside h3{margin:0 0 12px;font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--dim)}
.metric{margin:0 0 14px}
.metric .lab{display:flex;justify-content:space-between;font-size:11px;color:var(--dim);margin-bottom:4px}
.metric .lab b{color:var(--ink)}
.bar{height:8px;border-radius:6px;background:var(--panel2);overflow:hidden}
.bar > i{display:block;height:100%;border-radius:6px;background:linear-gradient(90deg,#6d28d9,#8b5cf6)}
.race > div{display:flex;align-items:center;gap:8px;margin:3px 0;font-size:11px;color:var(--dim)}
.race .rb{flex:1;height:7px;border-radius:5px;background:var(--panel2);overflow:hidden}
.race .rb > i{display:block;height:100%;background:#3b82f6}
.race .win{color:var(--ink)} .race .win .rb > i{background:var(--backed)}
.mix{display:flex;height:10px;border-radius:6px;overflow:hidden;border:1px solid var(--edge)}
.mix > i{display:block;height:100%}
.mix .evidenced{background:var(--evidenced)} .mix .intervention_backed{background:var(--backed)}
.mix .architecture_only{background:var(--arch)} .mix .attempted{background:var(--arch)} .mix .absent{background:var(--absent)}
.stat{display:flex;justify-content:space-between;font-size:11.5px;color:var(--dim);margin:3px 0}
.stat b{color:var(--ink)}
.timeline{position:sticky;bottom:0;z-index:6;display:flex;gap:4px;flex-wrap:wrap;justify-content:center;
  padding:12px 20px;background:rgba(8,11,17,.92);border-top:1px solid var(--edge)}
.cell{width:20px;height:20px;border-radius:5px;border:1px solid var(--edge);background:var(--panel2);cursor:pointer;
  font-size:10px;color:var(--dim);display:flex;align-items:center;justify-content:center}
.cell:hover{border-color:var(--accent)} .cell.on{background:var(--accent);color:#fff;border-color:var(--accent)}
.controls{display:flex;gap:8px;justify-content:center;padding:0 20px 40px}
button{background:var(--panel);color:var(--ink);border:1px solid var(--edge);border-radius:8px;padding:7px 14px;cursor:pointer;font:inherit}
button:hover{border-color:var(--accent)}
footer{max-width:1180px;margin:0 auto;padding:0 20px 40px;color:var(--dim);font-size:11.5px}
</style>
</head>
<body>
<header>
  <h1>Pneuma Voice <small>· __SUBJECT__ · <span id="mode"></span></small></h1>
  <div class="families" id="families"></div>
  <div class="badge" id="badge"></div>
</header>
<div class="layout">
  <main id="stream"></main>
  <aside>
    <h3>Internal state · <span id="panelTick">tick 0</span></h3>
    <div id="panel"></div>
  </aside>
</div>
<div class="controls">
  <button id="play">▶ Play</button>
  <button id="prev">‹ Prev</button>
  <button id="next">Next ›</button>
</div>
<div class="timeline" id="timeline"></div>
<footer>
  Grounded, receipt-bound thought stream. The evidence scorer never reads this prose;
  credit is a display label, not a claim. Italic lines are optional local-model elaboration
  (non-canonical). Click a line for its receipts; use the timeline to scrub.
</footer>
<script id="thought-stream-data" type="application/json">__DATA__</script>
<script>
(function(){
  var data = JSON.parse(document.getElementById("thought-stream-data").textContent);
  document.getElementById("mode").textContent = data.mode;
  document.getElementById("badge").textContent = "Evidence level " + data.evidence_level;
  var fam = document.getElementById("families");
  Object.keys(data.indicator_family_status).sort().forEach(function(k){
    var s = data.indicator_family_status[k];
    var d = document.createElement("span");
    d.className = "dot " + s;
    var ic = document.createElement("i"); d.appendChild(ic);
    d.appendChild(document.createTextNode(k.replace(/_/g," ")));
    d.title = k + ": " + s;
    fam.appendChild(d);
  });
  var CREDIT = ["intervention_backed","evidenced","architecture_only","attempted","absent"];
  var stream = document.getElementById("stream");
  var sections = [];
  data.ticks.forEach(function(tk){
    var sec = document.createElement("section");
    sec.className = "tick";
    var h = document.createElement("h2"); h.textContent = "Tick " + tk.tick; sec.appendChild(h);
    tk.lines.forEach(function(ln){
      var el = document.createElement("div");
      el.className = "line " + ln.credit_status;
      var head = document.createElement("div");
      var chip = document.createElement("span"); chip.className = "chip";
      var b = document.createElement("b"); b.textContent = ln.type;
      chip.appendChild(b); chip.appendChild(document.createTextNode(" · " + ln.credit_status));
      head.appendChild(chip);
      var txt = document.createElement("span");
      txt.textContent = ln.text;
      if(ln.voice_status === "voiced"){ txt.className = "voiced"; }
      head.appendChild(txt);
      if(ln.voice_status === "voiced"){
        var tag = document.createElement("span"); tag.className="tag"; tag.textContent="elaborated"; head.appendChild(tag);
      }
      el.appendChild(head);
      if(ln.receipts && ln.receipts.length){
        var tog = document.createElement("div"); tog.className="rtoggle";
        tog.textContent = "▸ receipts (" + ln.receipts.length + ")";
        var box = document.createElement("div"); box.className="receipts";
        ln.receipts.forEach(function(r){
          var row = document.createElement("div");
          var key = document.createElement("span"); key.textContent = r.field_path;
          var v = (r.value === null || r.value === undefined) ? "—" : String(r.value);
          row.appendChild(key); row.appendChild(document.createTextNode(" = " + v));
          box.appendChild(row);
        });
        tog.addEventListener("click", function(){
          box.classList.toggle("open");
          tog.textContent = (box.classList.contains("open") ? "▾" : "▸") + " receipts (" + ln.receipts.length + ")";
        });
        el.appendChild(tog); el.appendChild(box);
      }
      sec.appendChild(el);
    });
    stream.appendChild(sec);
    sections.push(sec);
  });

  var panel = document.getElementById("panel");
  var panelTick = document.getElementById("panelTick");
  function metric(label, valText, frac, cls){
    var m = document.createElement("div"); m.className="metric";
    var lab = document.createElement("div"); lab.className="lab";
    var l = document.createElement("span"); l.textContent = label;
    var vv = document.createElement("b"); vv.textContent = valText;
    lab.appendChild(l); lab.appendChild(vv); m.appendChild(lab);
    if(frac !== null){
      var bar = document.createElement("div"); bar.className="bar";
      var fill = document.createElement("i"); fill.style.width = Math.max(0,Math.min(1,frac))*100 + "%";
      bar.appendChild(fill); m.appendChild(bar);
    }
    return m;
  }
  function fmt(x){ return (x===null||x===undefined) ? "—" : (Math.round(x*100)/100).toFixed(2); }
  function renderPanel(i){
    var p = data.ticks[i].panel;
    panelTick.textContent = "tick " + data.ticks[i].tick;
    panel.textContent = "";
    panel.appendChild(metric("verification pressure", fmt(p.pressure), p.pressure===null?null:p.pressure));
    // salience race
    var terms = Object.keys(p.salience).sort();
    if(terms.length){
      var mx = Math.max.apply(null, terms.map(function(t){return p.salience[t];})) || 1;
      var race = document.createElement("div"); race.className="metric race";
      var lab = document.createElement("div"); lab.className="lab";
      var l=document.createElement("span"); l.textContent="workspace race";
      var w=document.createElement("b"); w.textContent = p.winner || "—"; lab.appendChild(l); lab.appendChild(w);
      race.appendChild(lab);
      terms.forEach(function(t){
        var row=document.createElement("div"); if(t===p.winner) row.className="win";
        var nm=document.createElement("span"); nm.textContent=t; nm.style.minWidth="88px";
        var rb=document.createElement("div"); rb.className="rb"; var fi=document.createElement("i");
        fi.style.width=(p.salience[t]/mx*100)+"%"; rb.appendChild(fi);
        var vn=document.createElement("span"); vn.textContent=fmt(p.salience[t]);
        row.appendChild(nm); row.appendChild(rb); row.appendChild(vn); race.appendChild(row);
      });
      panel.appendChild(race);
    }
    if(p.dominant_affect){
      panel.appendChild(metric("affect · "+p.dominant_affect.dim, fmt(p.dominant_affect.value), null));
    }
    var st=document.createElement("div"); st.className="metric";
    [["scar strength",p.scar_strength],["predicted error",p.predicted_error]].forEach(function(kv){
      var row=document.createElement("div"); row.className="stat";
      var a=document.createElement("span"); a.textContent=kv[0];
      var b=document.createElement("b"); b.textContent=fmt(kv[1]);
      row.appendChild(a); row.appendChild(b); st.appendChild(row);
    });
    panel.appendChild(st);
    // credit mix
    var total=0; CREDIT.forEach(function(c){ total += (p.credit_counts[c]||0); });
    if(total){
      var mm=document.createElement("div"); mm.className="metric";
      var lab=document.createElement("div"); lab.className="lab";
      var l=document.createElement("span"); l.textContent="credit mix"; var b=document.createElement("b"); b.textContent=total+" atoms";
      lab.appendChild(l); lab.appendChild(b); mm.appendChild(lab);
      var mix=document.createElement("div"); mix.className="mix";
      CREDIT.forEach(function(c){ var n=p.credit_counts[c]||0; if(!n) return;
        var seg=document.createElement("i"); seg.className=c; seg.style.width=(n/total*100)+"%"; seg.title=c+": "+n; mix.appendChild(seg); });
      mm.appendChild(mix); panel.appendChild(mm);
    }
    panel.appendChild(metric("evidence level", String(p.evidence_level), p.evidence_level/4));
  }

  var timeline = document.getElementById("timeline");
  var cells = [];
  data.ticks.forEach(function(tk,i){
    var c=document.createElement("div"); c.className="cell"; c.textContent=tk.tick;
    c.addEventListener("click", function(){ setActive(i); });
    timeline.appendChild(c); cells.push(c);
  });
  var active = 0;
  function setActive(i){
    active = i;
    sections.forEach(function(s,j){ s.classList.toggle("active", j===i); });
    cells.forEach(function(c,j){ c.classList.toggle("on", j===i); });
    renderPanel(i);
    sections[i].scrollIntoView({behavior:"smooth", block:"center"});
  }
  document.getElementById("next").addEventListener("click", function(){ setActive(Math.min(active+1, sections.length-1)); });
  document.getElementById("prev").addEventListener("click", function(){ setActive(Math.max(active-1, 0)); });
  document.getElementById("play").addEventListener("click", function(){
    var i=0; (function step(){ if(i>=sections.length) return; setActive(i); i++; setTimeout(step, 1100); })();
  });
  setActive(0);
})();
</script>
</body>
</html>
"""


def render_html(stream: dict) -> str:
    """Render a self-contained mind-monitor HTML document (deterministic payload)."""
    payload = monitor_payload(stream)
    data = json.dumps(payload, sort_keys=True, ensure_ascii=False)
    data = data.replace("</", "<\\/")
    subject = str(stream["subject"])
    return _TEMPLATE.replace("__DATA__", data).replace("__SUBJECT__", subject)


def write_monitor(stream: dict, out_path: str | Path) -> None:
    """Write the mind-monitor HTML to ``out_path`` (deterministic payload)."""
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_html(stream), encoding="utf-8", newline="\n")


__all__ = ["monitor_payload", "render_html", "write_monitor"]
